### ISSUE TITLE
"code":"api"

### ISSUE THREAD

**Issue by santiseijas** [tipsi/tipsi-stripe#755] opened 2021-04-23 14:41 UTC
hi everyone, i just want to ask what is the meaning of `errorCode: api`?? this is my error {"framesToPop":1,"nativeStackAndroid":[],"userInfo":null,"message":"Your card is not supported.","code":"api"} and we are getting this on createPaymentMethod with this card 6200 0000 0000 0005 on Spain.
Thank you so much!!

**Comment by plowman** [comment] 2021-04-29 22:29
Hey @santiseijas, this means the error code is coming back from the Stripe API and not from this library.

In your case, the problem is likely that you need to use a Spain-specific credit card test number. You can [see here](https://stripe.com/docs/testing#international-cards) for examples from each country.

**Comment by fbartho** [comment] 2023-06-20 20:24
Closing this ticket, so that new users don't think this project is still active.

Stripe does not want you using this, and you will find pain if you do; Please migrate to the official [@stripe/stripe-react-native](https://github.com/stripe/stripe-react-native) package, for your user's safety, and your developer's sanity!

See more: 
- https://github.com/tipsi/tipsi-stripe/issues/779
- https://github.com/tipsi/tipsi-stripe/issues/842

**Closed by fbartho** 2023-06-20 20:24 UTC
