### ISSUE TITLE
iOS: Support 0 values in ApplePayPaymentRequest - total

### ISSUE THREAD

**Issue by getsbydev** [tipsi/tipsi-stripe#492] opened 2019-06-24 12:56 UTC
## Before I have submitted the issue 
[x] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[x] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[x] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[x] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
I have a case where a user orders some items, and receives a discount which results in a total price of 0.
Currently if I try to set a 0 value, the native module throws an "Amount should be greater than 0" error.

According to the official Apple Pay documentation [ApplePayPaymentRequest - total](https://developer.apple.com/documentation/apple_pay_on_the_web/applepaypaymentrequest/1916119-total) also supports values to be equal 0. 

## Environment
* `tipsi-stripe` version: 7.5.0
* iOS or Android: iOS
* OS version: 12.2
* React-Native version: 0.59.9

## Error 
Error: Amount should be greater than 0
    at createErrorFromErrorData (NativeModules.js:155)
    at NativeModules.js:104
    at MessageQueue.__invokeCallback (MessageQueue.js:414)
    at MessageQueue.js:127
    at MessageQueue.__guard (MessageQueue.js:314)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:126)
    at debuggerWorker.js:80

## Code To Reproduce Issue
```
const options = {
        total_price: '0.00',
        currency_code: 'EUR',
        line_items: [
          {
            currency_code: 'EUR',
            description: 'Testitem',
            total_price: '1.00',
            unit_price: '1.00',
            quantity: '1'
          },
          {
            currency_code: 'EUR',
            description: 'Discount',
            total_price: '-1.00',
            unit_price: '-1.00',
            quantity: '1'
          }
        ]
      };

      const items = [
        {
          label: 'Testitem',
          amount: '1.00'
        },
        {
          label: 'Discount',
          amount: '-1.00'
        },
        {
          label: 'Pay company',
          amount: '0.00'
        }
      ];

      const token = await stripe.paymentRequestWithNativePay(options, items);
```

**Comment by fbartho** [comment] 2019-07-24 00:40
![image](https://user-images.githubusercontent.com/209712/61756387-858c0800-ad70-11e9-83ac-f0153a052a3b.png)
The documentation seems ambiguous -- I'm not sure it supports zero values.

Looking at the source code, the error is thrown here: https://github.com/tipsi/tipsi-stripe/blob/7ae12e4f8ef86e65bde032c5ffd32f5ee80c7e86/ios/TPSStripe/TPSStripeManager.m#L533-L537

So if you want to implement this, you should start there!

**Comment by fbartho** [comment] 2019-07-24 00:53
#duplicate of #479

**Comment by charlesTR** [comment] 2020-12-24 22:03
I tried to comment this code out, and it seems to be working fine:
- The bottom payment action sheet shows up as expected to confirm a payment of $0
- No exception thrown when confirming
- And a token is being returned

![Screen Shot 2020-12-24 at 1 57 15 PM](https://user-images.githubusercontent.com/10536110/103107196-cb49a180-45f0-11eb-807b-2a7ce4b0015e.png)

**Comment by fbartho** [comment] 2020-12-24 23:16
Great news @charlesTR!

**Closed** 2020-12-25 10:41 UTC
Labels: wont-fix
