### ISSUE TITLE
Unable to link  tipsi-stripe. 

### ISSUE THREAD

**Issue by eramudeep** [tipsi/tipsi-stripe#471] opened 2019-04-19 17:05 UTC
##see the screenshot attached.
this happens when i try to link it.
![image](https://user-images.githubusercontent.com/38516686/56434696-41ade080-62f3-11e9-91f9-4a7e38ff2026.png)

**Comment by yassinecc** [comment] 2019-04-23 14:13
Looks like an issue with react-native-cli, can you provide a repro case?

**Comment by dksami** [comment] 2019-05-06 10:00
Same Issue Here , Can any person help me with this.
You can just go create an empty react native project , and import the strip library and try to link it to reproduce.

**Comment by cybergrind** [comment] 2019-05-06 21:04
@dksami we have an example project that we're running during CI tests

https://github.com/tipsi/tipsi-stripe/blob/master/.travis/install.sh#L17

link is here and it's at least working. Probably some specific conditions are required to reproduce this

**Comment by dksami** [comment] 2019-05-11 06:36
"react-native": "0.59.3"
I tried in a new Project and I can confirm this issue exists, Sir.
![Capture](https://user-images.githubusercontent.com/29794630/57566020-f8781a80-73e0-11e9-86a9-51e5bb5816ef.PNG)

**Comment by 488taimoor** [comment] 2019-05-11 19:22
any solution ? i'm also getting same issue...

**Comment by cybergrind** [comment] 2019-05-11 19:29
@dksami probably this is related to windows, could you please try to do the same steps on Linux?

**Comment by dksami** [comment] 2019-05-11 19:49
Okay ill try thing on mac, have no linux environment.

**Comment by 488taimoor** [comment] 2019-05-16 20:52
@cybergrind i'm getting the same issue when i try to integrate with windows.

**Comment by cybergrind** [comment] 2019-05-16 21:00
@488taimoor I don't think that it has worked at all on windows.
So someone needs to dig this issue, fix and submit PR because I'm not sure that we will have this done in the nearterm

**Comment by dksami** [comment] 2019-05-20 08:47
Confirmed It only does not work on Windows at all. On Mac Os, it's Working fine.

**Comment by cybergrind** [comment] 2019-05-20 08:51
@dksami thank you!

**Comment by dksami** [comment] 2019-05-20 09:00
is there any solution or i have to link it via mac and then use it on pc :"D?

**Comment by cybergrind** [comment] 2019-05-20 09:05
@dksami if you can fix it on your pc and then submit a PR with a fix this will help a lot. 
otherwise, there are no other variants right now. I've put warning about it in the linking section https://tipsi.github.io/tipsi-stripe/docs/linking.html but not quite sure when someone decides to dig this.

**Comment by dksami** [comment] 2019-05-23 20:46
The error is being fixed after a couple of days of Research, I have committed a change. As fast as admin will approve that. linking will start to work for everyone until then.
https://github.com/dksami/tipsi-stripe .

**Comment by eramudeep** [comment] 2019-05-24 03:39
Is a great news.

**Comment by cybergrind** [comment] 2019-05-24 12:24
@dksami even if it works on windows it definitely breaks some cases that are handled by commands you've removed.
So probably it needs to be fixed in some other way.

**Comment by dksami** [comment] 2019-05-24 13:31
I will loook into it by manual linking and let you know if it will effect or not.

**Comment by cybergrind** [comment] 2019-05-24 14:00
@dksami it looks like the main issue here - Windows doesn't know how to run bash scripts, so they must be ported to .js and executed with node instead of bash

**Comment by dksami** [comment] 2019-05-24 14:12
That might be the case, you try porting then i will try doing that. Even if it links correctly with out using scripts its a success.

**Closed** 2020-12-25 10:44 UTC
Labels: wont-fix
