### ISSUE TITLE
Apple Pay Not Configured. Payment failing on real device and simulator.

### ISSUE THREAD

**Issue by dominicvitucci1** [tipsi/tipsi-stripe#333] opened 2018-07-16 02:52 UTC
Hello! 

When trying to complete a payment request with apple pay I'm presented with this error message every time.

```
Error: Apple Pay is not configured
    at createErrorFromErrorData (NativeModules.js:121)
    at NativeModules.js:78
    at MessageQueue.__invokeCallback (MessageQueue.js:398)
    at MessageQueue.js:137
    at MessageQueue.__guardSafe (MessageQueue.js:314)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:136)
    at debuggerWorker.js:70
```

This happens in the simulator and on a real device. I've tried bringing up the Apple Pay setup screen but even when using `stripe.openApplePaySetup()` nothing happens.

Thank you for any help!

**Comment by isnifer** [comment] 2018-07-16 08:10
Hi, @dominicvitucci1! Could you please more information? 
Add gif with your steps to see and reproduce the issue?

**Comment by dominicvitucci1** [comment] 2018-07-17 13:23
@isnifer I can add a GIF later today but the steps to reproduce are simple. When I click my button to execute `stripe.paymentRequestWithApplePay(items)` I get a caught error that shows the dialog above in the console. Does that make sense?

**Comment by jrdzha** [comment] 2018-07-18 03:37
Did you setup the merchant ID / certificate correctly? 
[https://stripe.com/docs/apple-pay/apps](url)

Also, after setting up your merchant ID, did you set it within your code?
```
stripe.setOptions({
  publishableKey: 'stripe test thing',
  merchantId: 'merchant.com.yourwebsite',
  androidPayMode: 'test',
});
```

**Comment by dominicvitucci1** [comment] 2018-07-18 13:30
@jrdzha I just redid my merchant ID/certificate setup to be sure but I'm still having the same issue. I don't have any trouble processing credit cards just Apple Pay

**Comment by jrdzha** [comment] 2018-07-18 18:53
@dominicvitucci1 Processing credit cards shouldn't require setting up the merchant ID / certificate. Only Apple Pay will be affected by this. Just to be sure, did you set up the certificate using what Stripe provided? AKA, if you go in your Stripe dashboard under Apple Pay, do you see your certificate there?

**Comment by dominicvitucci1** [comment] 2018-07-18 19:44
@jrdzha When I check my Stripe Dashboard I can see the certificate there. When Setting up Apple Pay I followed the instructions from Stripe exactly, including adding my merchant ID to XCode and the developer portal

**Comment by jrdzha** [comment] 2018-07-18 21:30
@dominicvitucci1 That's strange.. If you think your setup is correct, then it's hard to tell what's wrong without seeing some code. Could you cut out a few relevant lines so I can take a look?

**Comment by isnifer** [comment] 2018-07-19 08:43
@dominicvitucci1 and please record a gif with your experiment because when environment is correct`stripe.paymentRequestWithApplePay` works perfect

**Comment by dominicvitucci1** [comment] 2018-07-19 13:43
```
 async getTokenApplePay() {
    let items = [];

    cart.map(item => {
      let itemTotal = item.ItemPrice * item.Quantity;
      let object = {
        label: item.ItemName,
        amount: String(itemTotal)
      };

      items.push(object);
    });

      items.push({
        label: "Vendor",
        amount: String(
          this.state.orderTotal
        )
      });

      const token = await stripe.paymentRequestWithApplePay(items);

      this.setState({ loading: true });
      totalOrder.toFixed(2);
      this.writeToken(token, totalOrder, cart, "pending");

    } catch (error) {
      // Or cancel if an error occurred
      console.log(error);
      }

      stripe.cancelApplePayRequest();
    }
  }
```

![error gif](https://user-images.githubusercontent.com/8997930/42946026-8de58c56-8b2f-11e8-99fd-b42bcc3fe438.gif)


The code above is called when I press the blue button in the GIF above. The console output displays the above message. Please let me know if I can provide any additional information.

**Comment by dominicvitucci1** [comment] 2018-07-19 22:48
@jrdzha I think there might have been. The updated code is below, but unfortunately it still throws the same error.

```
async getTokenApplePay() {
    let items = [];

    cart.map(item => {
      let itemTotal = item.ItemPrice * item.Quantity;
      let object = {
        label: item.ItemName,
        amount: String(itemTotal)
      };

      items.push(object);
    });

    try {

      items.push({
        label: "Vendor",
        amount: String(
          this.state.orderTotal 
        )
      });

      const token = await stripe.paymentRequestWithApplePay(items);

      this.setState({ loading: true });
      totalOrder.toFixed(2);
      this.writeToken(token, totalOrder, cart, "pending");

    } catch (error) {
      console.log(error);

      stripe.cancelApplePayRequest();
    }
  }
```

**Comment by jrdzha** [comment] 2018-07-20 05:26
@dominicvitucci1 

I know I asked this already, but you are including this at the top of the .js file right. Missing this will throw the error you're getting.

```
stripe.setOptions({
  publishableKey: 'stripe test thing',
  merchantId: 'merchant.com.yourwebsite',
  androidPayMode: 'test',
});
```

I don't see anything wrong with the code you have showed. Can you include your setOptions and import too?

**Comment by dominicvitucci1** [comment] 2018-07-20 13:30
@jrdzha Thanks so much for all your help! My import statement and setOptions are below. I still cannot figure out what else the error could be from.

```
import stripe from "tipsi-stripe";

stripe.setOptions({
  publishableKey: "My Stripe Publishable Key",
  merchantId: "merchant.com.CompanyName", // Optional
  androidPayMode: "test" // Android only
});
```

**Comment by jrdzha** [comment] 2018-07-20 18:50
@dominicvitucci1 

At this point, I'm not sure what could possibly be wrong. Have you tried creating a new React Native project and testing just tipsi-stripe? AKA a completely clean build?

**Comment by isnifer** [comment] 2018-07-23 12:39
@dominicvitucci1 just to be clear, your Apple Pay button should look like Apple Pay button — https://developer.apple.com/design/human-interface-guidelines/apple-pay/buttons-and-marks/buttons/

**Comment by isnifer** [comment] 2018-07-23 12:50
@dominicvitucci1 next, let me help you with your example:
```js
async getTokenApplePay() {
  // I hope cart in this scope
  const items = cart.map(item => {
    const itemTotal = item.ItemPrice * item.Quantity;

    return {
      label: item.ItemName,
      amount: String(itemTotal)
    };
  });

  items.push({
    label: "Vendor",
    amount: String(this.state.orderTotal)
  });

  const token = await stripe.paymentRequestWithApplePay(items);

  this.setState({ loading: true });
  totalOrder.toFixed(2);
  this.writeToken(token, totalOrder, cart, "pending");

  } catch (error) {
    // Cancel Apple Pay request
    const { TPSErrorDomain, TPSErrorCodeUserCancel } = stripe
    const userCanceled = error.domain === TPSErrorDomain && error.code === TPSErrorCodeUserCancel

    if (!userCanceled) {
      await stripe.cancelApplePayRequest()
    }
  }
}
```
If you're using a `map` you do need to push inside it, just do return and assign value to `items`.
If you would like to push — use `forEach` method or `for`-loop or `for-of`-loop.

**Comment by isnifer** [comment] 2018-07-23 13:34
@dominicvitucci1 what `await stripe.deviceSupportsApplePay()` returns?

**Comment by isnifer** [comment] 2018-09-01 21:32
@dominicvitucci1 *5.6.0* should help you. I'm closing this issue. Feel free to open a new one

**Closed by isnifer** 2018-09-01 21:32 UTC
