### ISSUE TITLE
cannot access zzbfm class file for com.google.android.gms.internal.zzbfm not found

### ISSUE THREAD

**Issue by ajaykumar97** [tipsi/tipsi-stripe#443] opened 2019-02-27 11:59 UTC
## The problem
I have install tipsi-stripe for iOS and android. on iOS, it is working fine. but on android, when I build the project, it gives me the following error in android studio:
`cannot access zzbfm: class file for com.google.android.gms.internal.zzbfm not found`
## Environment
* `tipsi-stripe` version: 7.4.0
* iOS or Android: android
* OS version: 8
* React-Native version: 0.57.3
* (Android only) `com.google.firebase:firebase-core` version: 16.0.0
* (Android only) `com.google.android.gms:play-services-base` version: 16.0.0

For `Android`, please provide the following sections from `android/app/build.gradle`:
* android.compileSdkVersion: 27
* android.buildToolsVersion: 27.0.3
* android.defaultConfig.minSdkVersion: 16
* android.defaultConfig.targetSdkVersion: 26
* android.defaultConfig.multiDexEnabled: true

**Comment by cybergrind** [comment] 2019-02-28 09:28
Looks like duplicate of #442

**Closed by cybergrind** 2019-02-28 09:28 UTC

**Comment by vcheer1** [comment] 2019-08-29 11:04
1)Ensure to replace + version to dynamic version number
2)Ensure your android.compileSdkVersion: 27 is same as android.defaultConfig.targetSdkVersion: 27
3)Update your libraries to update version. This is important to retrieve latest data from the server and keep your apps up-to-date.

I strong believe this will help.

Thanks

Chuks from LightUP Creativity Solutions

**Comment by anunes9** [comment] 2020-04-24 16:20
Hey, got the same error after updating to Android X, any suggestion?
