### ISSUE TITLE
Support aapt2 (Android Plugin for Gradle 3.2 - Android App Bundle)

### ISSUE THREAD

**Issue by squirly** [tipsi/tipsi-stripe#346] opened 2018-07-30 18:44 UTC
This project is very close to being able to support building with [aapt2](https://android.googlesource.com/platform/frameworks/base/+/master/tools/aapt2/readme.md), which is a requirement for [Android App Bundles](https://developer.android.com/platform/technology/app-bundle/).

The only [issue is invalid resource XML in a sub-dependency](https://github.com/tipsi/CreditCardEntry/pull/5).

## To Do

- [x] @isnifer Merge https://github.com/tipsi/CreditCardEntry/pull/5
- [x] @isnifer Release https://github.com/tipsi/CreditCardEntry
- [ ] Update `CreditCardEntry` dependency https://github.com/tipsi/tipsi-stripe/blob/339cea10bc7c45b341154c37d3ef4d96db6cc906/android/build.gradle#L33

**Comment by paintedbicycle** [comment] 2018-08-15 19:59
Ugh, just spent hours bumping up against this without knowing what it was.

I can't seem to build without aapt2 and now with this issue, I can't build with aapt2.

Is there a temporary work around? I can't find where the dependency (CreditCardEntry) shows up in my project in order to edit the files manually

**Comment by isnifer** [comment] 2018-08-15 20:15
@paintedbicycle Hi! CreditCardEntry is a dependency of `tipsi-stripe`

**Comment by paintedbicycle** [comment] 2018-08-15 20:19
@isnifer Hey - yep, sorry for not understanding but I'm not sure what that means in terms of if I can or cannot find and edit it locally.

I can't see it in node_modules and I can't see it in Android Studio inside the Tipis-Stripe package. I did a basic search but couldn't find the files. I'm assuming it's being included as a dependency fine since my debug app will build, but I'm trying to edit the files as in the pull request above so that I can build for release, but cannot find the CreditCardEntry files locally to edit.

**Comment by paintedbicycle** [comment] 2018-08-15 20:48
Yes, I see the inclusion of the decency. But I need to edit the dependency files so that I can build and release my app. But it doesn't look like it's possible - as you said, perhaps it's downloaded each build.

Will this AAPT2 issue be a priority for your team? It appears as though it's editing just a few strings...

**Comment by squirly** [comment] 2018-08-17 23:16
I am currently working around this by modifying the dependencies in this report in my `settings.gradle` file:
```
FileTree propFiles = fileTree('./node_modules/tipsi-stripe/android/build.gradle') {}
String regex = "'com.github.tipsi:CreditCardEntry:.+'"
propFiles.each { File propFile ->
    String content = propFile.getText()
    content = content.replaceAll(regex, "'com.github.Storr-co:CreditCardEntry:fix-id-items-SNAPSHOT'")
    propFile.setText(content)
}
```

**Comment by paintedbicycle** [comment] 2018-08-18 08:12
Thanks for the reply @squirly I really appreciate the follow up! I'll look into this.

**Comment by valerybodak** [comment] 2018-09-27 14:42
@squirly 

How can I apply your code? 

```
FileTree propFiles = fileTree('./node_modules/tipsi-stripe/android/build.gradle') {}
String regex = "'com.github.tipsi:CreditCardEntry:.+'"
propFiles.each { File propFile ->
    String content = propFile.getText()
    content = content.replaceAll(regex, "'com.github.Storr-co:CreditCardEntry:fix-id-items-SNAPSHOT'")
    propFile.setText(content)
}
```

Could you please provide your settings.gradle.

Thanks in advance.

**Comment by squirly** [comment] 2018-09-27 16:55
If you look at the `TODO`s above it explains how to fix the issue. Starting with merging https://github.com/tipsi/CreditCardEntry/pull/5

**Comment by paintedbicycle** [comment] 2018-10-23 17:17
Hi again,

Tipsi-Stripe stops apps from building with AAPT2 enabled.

We've been seeing this warning for months:

```
The option 'android.enableAapt2' is deprecated and should not be used anymore.
Use 'android.enableAapt2=true' to remove this warning.
It will be removed at the end of 2018..
```

Android Studio is currently using Gradle Plugin 3.2.1. And if you try to use the next version of Gradle plugin (3.3.0+), you get:

```
The following project options are deprecated and have been removed: 
android.enableAapt2
This property has no effect, AAPT2 is now always used.
```
For a list of Gradle plugin releases to test with: https://mvnrepository.com/artifact/com.android.tools.build/gradle?repo=google

With that error the app won't build. With AAPT2 enabled, builds produce a variety of error messages with Tipsi Stripe, the most common on being the res / merged / id / strings / error from CreditCardEntry

This pull request is open: https://github.com/tipsi/CreditCardEntry/pull/5 and as far as I can tell, is the solution to fixing this issue.

I'd imagine the next version of Android Studio is going to bump from Gradle 3.2.x to 3.3.x and then no-one using this library will be able to build their app. Seems like something that will need attention soon.

Paul

**Comment by digicontributer** [comment] 2018-10-23 21:39
Yes I would love to see this merged/fixed so I can run builds without manual intervention.

**Comment by cybergrind** [comment] 2018-10-29 09:55
tipsi/CreditCardEntry#5 is merged now

@digicontributer / @paintedbicycle / @squirly it would be great if anyone can confirm that everything is ok with tipsi-stripe 6+

**Comment by paintedbicycle** [comment] 2018-11-16 17:52
Hey @cybergrind sorry it took me so long to do a build. I can confirm the fixed worked for me.

Thank you!

**Comment by cybergrind** [comment] 2018-11-16 18:54
hi @paintedbicycle. that's great so going to close issue

**Closed by cybergrind** 2018-11-16 18:54 UTC
