### ISSUE TITLE
paymentRequestWithCardForm Crashing App

### ISSUE THREAD

**Issue by jaysig** [tipsi/tipsi-stripe#82] opened 2017-07-06 23:29 UTC
I am running into an issue when I try to call paymentRequestWithCardForm. I get the following error, which crashes my app.
```
'*** -[__NSCFConstantString stringByAppendingString:]: nil argument' was thrown while invoking paymentRequestWithCardForm on target TPSStripeManager with params (
        {
        requiredBillingAddressFields = full;
        smsAutofillDisabled = 1;
        theme =         {
        };
    },
    70,
    71
)
```
Function Invocation 
```
handleCardPayPress = async () => {
      try {
        this.setState({
          loading: true,
          token: null,
        })
        console.log(stripe,'inner stripe');
        const token = stripe.paymentRequestWithCardForm({
          // Only iOS support this options
          smsAutofillDisabled: true,
          requiredBillingAddressFields: 'full',
          prefilledInformation: {
            billingAddress: {
              name: 'Gunilla Haugeh',
              line1: 'Canary Place',
              line2: '3',
              city: 'Macon',
              state: 'Georgia',
              country: 'US',
              postalCode: '31217',
              email: 'ghaugeh0@printfriendly.com',
            },
          },
        })

```
How I call it

```
                <ARButton
                    style={[styles.changeBtn,styles.btn]}
                    title="CHANGE PAYMENT INFORMATION"
                    type={2}
                    onPress={this.handleCardPayPress}
                    // onPress={()=>this.props.navigation.navigate('PaymentInfo')}
                />
```

**Comment by itsmepetrov** [comment] 2017-07-06 23:42
@dmytrozavgorodniy please take a look

**Comment by pongponglau** [comment] 2017-07-10 04:43
I encounter the same issue in iphone 7. However, there is no problem in simulator.

Thanks for your advice.

**Comment by dmytrozavgorodniy** [comment] 2017-07-19 13:23
Hi everyone! Sorry for late response.
@jaysig, @pongponglau 
Could you please provide more information about your environment:
What version of Stripe framework you are using in our app? (you can check Stripe pod version in your Podfile)
Which version of iOS you are using for testing?

Also, maybe you can provide, what information you are input in form.

**Comment by pongponglau** [comment] 2017-07-20 02:25
I remove the card preset json information when calling paymentRequestWithCardForm, then the problem is solved. If not, something like listview index out of range error will return.

Cheers

**Comment by jaysig** [comment] 2017-07-22 16:22
Hi @dmytrozavgorodniy,
I'm using Stripe 10.1.0
I am just running it on the simulator; so, the latest version of iOS

I can not even get the form to render, it just crashes when I try to initialize it. I ended up just using PaymentCardTextField and that worked fine.

**Comment by viczzh** [comment] 2017-07-27 10:12
Having the same issue. Any solutions?

**Comment by isnifer** [comment] 2017-07-27 11:09
@viczzh it would be nice if you can create small repo that reproduces this error

**Comment by Uki19** [comment] 2017-08-01 23:28
I had this issue, the problem was that I forgot to set publishableKey. Don't forget to add 
`stripe.init({
    publishableKey: 'pk_test_UnK1dsvDzXfiGUwHBRFnOHxU',
});`

**Comment by isnifer** [comment] 2017-08-31 14:53
@jaysig @viczzh guys did you solve this issue?

**Comment by isnifer** [comment] 2017-11-06 14:22
Fixed in #109

**Closed by isnifer** 2017-11-06 14:22 UTC
