### ISSUE TITLE
 'Stripe/Stripe.h' file not found

### ISSUE THREAD

**Issue by ignivaankushrishi** [tipsi/tipsi-stripe#11] opened 2016-12-17 06:31 UTC
Hi,

I am getting this error while building the application in xcode:  `'Stripe/Stripe.h' file not found`

I have integrated this package manually in xcode.

here is the screenshot:
![screen shot 2016-12-17 at 12 30 23 pm](https://cloud.githubusercontent.com/assets/16954229/21285071/a7a7c95e-c454-11e6-9f12-b8f617d9efa2.png)

**Comment by isnifer** [comment] 2016-12-17 11:27
@ignivaankushrishi did you try `react-native link` command ?

**Comment by itsmepetrov** [comment] 2016-12-18 15:10
Hi, @ignivaankushrishi, thank you for your interest in our module!

It looks like you did not setup CocoaPods dependencies:

- Setup your `Podfile` like the included [example/ios/Podfile](example/ios/Podfile)
- Then run `pod install` in `ios` directory

**Comment by shyaniv7** [comment] 2016-12-23 23:32
i am getting the same error and the suggestions above did not work

**Comment by densa** [comment] 2016-12-25 00:11
@ignivaankushrishi @shyaniv7 are you open xcworkspace not xcodeproj ?

**Comment by shyaniv7** [comment] 2016-12-25 00:13
@densa i have using the xcodeproj file

**Comment by densa** [comment] 2016-12-25 09:12
@shyaniv7 you have to use workspace file because of pods

**Comment by cybergrind** [comment] 2017-01-12 09:48
@shyaniv7 I belive this issue was resolved, so closing it

**Closed by cybergrind** 2017-01-12 09:48 UTC
Labels: question

**Comment by magneticz** [comment] 2017-02-08 12:51
Hi, thank you guys for great work
Strangely, I am getting this error. I did everything according to the instructions, installed through npm and run react-native link. But it still gives me the same error

**Comment by itsmepetrov** [comment] 2017-02-08 13:20
Hi, @magneticz, which version of react-native do you use? Are you open `.xcworkspace` file to build application?

**Comment by magneticz** [comment] 2017-02-08 13:55
hi @itsmepetrov, I am using react-native 0.41.2. I usually build with react-native run-ios, but in this case i tried to build through xcode using .xcworkspace, so yes, i used .xcworkspace

**Comment by itsmepetrov** [comment] 2017-02-08 16:16
I noticed some problems with link on `0.41.2` version, could you show your `ios/Podfile` file , please?

**Comment by magneticz** [comment] 2017-02-08 16:49
sure, here it is
```
platform :ios, '8.0'
target 'app' do
  use_frameworks!

  pod 'Firebase/Messaging'
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'
  pod 'Firebase/Core'

  target 'appTests' do
    inherit! :search_paths
  end

end
pod 'Stripe', '~> 9.2.0'
```

**Comment by itsmepetrov** [comment] 2017-02-08 17:08
Could you move `pod 'Stripe', '~> 9.2.0'` under `app` target, right after `pod 'Firebase/Core'` and then install pods again: `pod install` in `ios` directory.

**Comment by magneticz** [comment] 2017-02-08 17:17
not working, i moved and did `pod install`, it didn't work then i tried to do `react-native link` but it still didn't work, same file not found error. I looked into the header search path, to make sure paths in the readme are there and they are there, so i do not know why the file is still not found. And I am not good with ios development to dig deeper

**Comment by sergeyzhukov** [comment] 2017-02-08 17:46
Do you have folder Pods/Stripe folder inside ios folder? And try to change Podfile to be looking like this

```
platform :ios, '8.0'
target 'app' do
  use_frameworks!
  pod 'Stripe', '~> 9.2.0'
  pod 'Firebase/Messaging'
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'
  pod 'Firebase/Core'
  inherit! :search_paths

  target 'appTests' do
    inherit! :search_paths
  end

end
```

And make sure you have correctly linked libpods like this (libPods-StripeTest.a, StripeTest is name of my target):

<img width="697" alt="screen shot 2017-02-08 at 09 44 57" src="https://cloud.githubusercontent.com/assets/1446268/22749789/600a4d8e-ede3-11e6-9ae0-06a454a1ddd2.png">

**Comment by magneticz** [comment] 2017-02-09 08:21
I have Pods/Stripe folder and i tried changing podfile.
the libTPSStripe.a is also there, but i do not have libPods-StripeTest.a linked. I couldn't find any libPods file to link, maybe that's the problem.

**Comment by sergeyzhukov** [comment] 2017-02-09 14:19
You can try to add this lib by tapping on + and select libPods-StripeTest.a

<img width="607" alt="screen shot 2017-02-09 at 06 18 07" src="https://cloud.githubusercontent.com/assets/1446268/22786999/9bbb3418-ee8f-11e6-8195-7b39cb319477.png">

Also please be sure that you are opening xcworkspace file (not project) and you have pods integrated in workspace like this 

<img width="264" alt="screen shot 2017-02-09 at 06 19 30" src="https://cloud.githubusercontent.com/assets/1446268/22787044/c1d68062-ee8f-11e6-9a50-b4eb72af649b.png">

**Comment by ezos86** [comment] 2017-05-22 07:43
This issue is not resolved, this library has been a nightmare to work with, constant missing files, and cross generation dependencies that seem to sometimes appear and sometimes not.

**Comment by cybergrind** [comment] 2017-05-22 09:50
@ezos86 maybe we're missing something and you can point us that?

If you can provide us reproducible steps, eg. share repo where it isn't working it would be great and would help us fix it.
We already have CI tests that are doing everything from scratch so we can be sure that it works at least under some circumstances. With you help, we can find other cases and fix them too.

**Comment by mienaikoe** [comment] 2017-06-03 04:15
In my case I can't use `inherit! :search_paths` because it causes an linking error in react-native-fcm. is there a workaround to using that directive?

**Comment by ignivaankushrishi** [comment] 2017-06-08 05:36
@cybergrind this issue still exists if we do not use pods. I want to add this library without using pods. So, this issue should not be closed like this. you should update your library so that it should work error free.

**Comment by GregTheGreek** [comment] 2017-06-08 06:27
Solid library but it's riddled with bugs

**Comment by isnifer** [comment] 2017-06-08 06:31
@ignivaankushrishi you need to use pods, cause you need Stripe Pod. 
> you should update your library so that it should work error free.  

You might help us, PRs welcome!

**Comment by isnifer** [comment] 2017-06-24 20:00
@ignivaankushrishi @GregTheGreek @mienaikoe @ezos86 @magneticz @shyaniv7 please, try 3.2.0

**Comment by SamiChab** [comment] 2017-11-17 16:36
Hey! 
I'm using `tispi-stripe@4.1.2`
I used `react-native link` (so no PodFile) and I get the same error.
I tried to :
- clean the build folder in XCode
- link `tipsi-stripe` again
- delete the `node_modules` folder ad run `npm install` again
- build the app again


I still get the same error ('Stripe/Stripe.h' file not found) as I build this in XCode.
I think the issue should be re-opened, considering the amount of people in the same case than me.

**Comment by isnifer** [comment] 2017-11-17 17:32
@SamiChab Hey! Show me your Podfile and Podfile.lock. Also, please tell me how are building your app? Are you using workspace instead of project?

**Comment by SamiChab** [comment] 2017-11-20 15:48
@isnifer thanks for your answer.
I was not using PodFile as I posted this message. It would be really cool if it worked with `react-native link`.

**Comment by isnifer** [comment] 2017-11-20 16:59
@SamiChab once again, you should use Podfile. It creates automatically while `react-native link`

**Comment by isnifer** [comment] 2017-11-20 17:16
@SamiChab please read https://github.com/tipsi/tipsi-stripe#ios-1

**Comment by SamiChab** [comment] 2017-11-20 17:22
Okay, I understand now that I didn't had to choose between `react-native link` or `CocoaPods` or `Manual`, but do all of them. Sorry for the inconvenience

**Comment by isnifer** [comment] 2017-11-20 17:24
@SamiChab after linking `tipsi-stripe` use workspace instead of project to build an app

**Comment by SamiChab** [comment] 2017-11-20 17:34
@isnifer You mean in XCode?

**Comment by isnifer** [comment] 2017-11-20 17:34
@SamiChab Yes

**Comment by cheema38** [comment] 2017-11-21 05:32
I have to agree with above comments, this library is finicky and a pain to get set up. great potential for RN but with the difficulty installing and having to link and use .xcworkspace and install pods,  im going back to the API and fetch :-(

**Comment by isnifer** [comment] 2017-11-21 06:52
So, @cheema38 all great libraries need to be linked if they are using native code

**Comment by GregTheGreek** [comment] 2017-11-21 07:31
@cheema38  Linking shouldn't be an issue for most libraries. I can't comment anymore on this one since I haven't used it in a very long time (although I'm willing to give it another chance). For whatever reason, the old version was very buggy when I would try and install it. If you have problems linking any library, you most likely are doing something wrong with your ios setup or you aren't using .workspace post linking.

@isnifer Make sure to check versions of RN people are using, that usually solves a lot of issues, and you can probably close more that way.

**Comment by isnifer** [comment] 2017-11-21 07:34
@GregTheGreek we are planning to remove automatic linking for `tipsi-stripe`, cause manual linking much simpler than we are doing in scripts. Usually, people are using project file instead of workspace, that's why problem exists

**Comment by wkwyatt** [comment] 2018-04-19 21:07
Has there been any resolution to this that is consistent?  I have `tipsi-stripe` installed and I'm getting the error:

 `node_modules/tipsi-stripe/ios/TPSStripe/TPSCardField.h:10:9: 'Stripe/Stripe.h' file not found` 

I am using `react-native 0.48`
installing with `react-native link tipsi-stripe`
and the Stripe version in my Podfile is `pod 'Stripe', '~> 11.2.0'`

**Comment by isnifer** [comment] 2018-04-19 21:13
@wkwyatt Hi! Did you start a **workspace** to run your app?

**Comment by wkwyatt** [comment] 2018-04-20 14:48
I followed the steps exactly and I am still getting the same error.  Am I missing something? 
![screen shot 2018-04-20 at 10 35 40 am](https://user-images.githubusercontent.com/13364964/39057842-438fcdd0-4488-11e8-9335-0b8050aa1d2c.png)


- Add TPSStipe to the Libraries folder 
![screen shot 2018-04-20 at 10 43 50 am](https://user-images.githubusercontent.com/13364964/39057709-e92c30cc-4487-11e8-9f2c-9808a788d377.png)

- Link binary
![screen shot 2018-04-20 at 10 35 03 am](https://user-images.githubusercontent.com/13364964/39057739-fe1dea16-4487-11e8-9dd5-84887e8cb200.png)

- add Header Search Paths (I tried recursive and non-recursive)
![screen shot 2018-04-20 at 10 34 15 am](https://user-images.githubusercontent.com/13364964/39057801-26ffeee8-4488-11e8-87a7-6762c4a35466.png)

**Comment by isnifer** [comment] 2018-04-20 15:15
@wkwyatt show me log of `pod install` inside your `ios` folder

**Comment by wkwyatt** [comment] 2018-04-20 16:06
![pi_img](https://user-images.githubusercontent.com/13364964/39061719-3e990034-4493-11e8-8eec-436741e00562.png)

**Comment by wkwyatt** [comment] 2018-04-20 16:07
![pi_img](https://user-images.githubusercontent.com/13364964/39061759-5d8e7366-4493-11e8-903d-e62711bea4e6.png)

**Comment by brilliantjc** [comment] 2018-05-25 18:17
@newah after copied the example file to a different location, error changed to : Could not install from ".." as it does not contain a package.json file

**Comment by isnifer** [comment] 2018-05-26 08:08
@brilliantjc just don't move it

**Comment by newah** [comment] 2018-05-26 16:43
@brilliantjc you need the whole react-native project - with package.json . Then from project root, install npm dependency tipsi-stripe - just like you do in any other RN project :)

Maybe you only copied ios folder, or xcode file or something... But you need the whole RN example project :)

**Comment by ankitgauravapporio** [comment] 2019-08-12 12:11
I am doing it by manual liking , followed each steps , still getting the error as 'Stripe/Stripe.h' file not found, can't afford to use pod , due to other dependencies.need you help / explanation
